# Generated by Django 6.0.7 on 2026-07-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='start_date',
        ),
    ]
