# Generated by Django 6.0.7 on 2026-07-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_remove_academicyear_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='academic_year',
        ),
    ]
