# Generated by Django 6.0.7 on 2026-07-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='academic_year',
        ),
    ]
