# Generated by Django 6.0.7 on 2026-07-27 11:57

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_subject_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 27, 11, 57, 50, 454984, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
